### ISSUE TITLE
HQ flag does not use flagTexture

### ISSUE THREAD

**Issue by bumbummen99** [official-antistasi-community/A3-Antistasi#1827] opened 2021-03-31 18:18 UTC
**Describe the bug**
The flag texture defined in the template files is only being used for garrisons, not for the HQ.

**To Reproduce**
Start a new mission and look at the flag.

**Expected behaviour**
Should be the same as the texture defined in the `flagTexture` template variable.

**Screenshots**
Hard to show with screenshots, it is just the default flag 😅 

**Environment (please complete the following information):**
Version: Latest master & 2.4 relase tag
Map (specify if Altis Blufor): Applies to any map

* [x] LAN Hosted
* [x] Private dedicated server
* [x] Private dedicated server with Headless client(s)
* [ ] Community Server 1
* [ ] Community Server 2
* [ ] Community Test Server
* [ ] Community Test Server 2

Modset:
RHS & ACRE2

Time the bug occurred (Please leave in GMT+0):
Every time i start a new Antistasi campaign

**Additional context**
Normally that bug is not noticeable as people normally do not modify the source / template files but just play the mission.

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

**Comment by Lazejun** [comment] 2021-04-01 18:00
Duplicate of #724

**Comment by Bob-Murphy** [comment] 2021-04-01 18:21
Fuck, that's on me.
Should have said "search the existing issues if there already is one for that problem and link it and if not, create one and link it" instead of "create one and link it".

**Comment by killerswin2** [comment] 2022-06-28 20:05
no one closed this one yet, but yes the HQ flag is now the correct flag texture.

**Closed by killerswin2** 2022-06-28 20:05 UTC
Labels: bug
