### ISSUE TITLE
Templating updates

### ISSUE THREAD

**Issue by SonorousMeerkat** [official-antistasi-community/A3-Antistasi#197] opened 2019-08-27 14:56 UTC
So I missed a few things during the RHS update that i want to address.
There are a bunch of new explosives and mines that should be added to their respective ammoboxes as well as a general rewrite of the units that the AFRF use. (currently only the navy is used) 
I also want to move the starting vests stuff into templates to reduce vanilla gear use in modded games where there is plenty of added equipment to use.
And to top it off, there are a load of new grenades that the Rebels could have access to, including but not limited to, a Willy Pete grenade and various grenades of WW2 vintage.

I will start this work as soon as Pot finishes hit template changes.

**Comment by SonorousMeerkat** [comment] 2019-08-27 14:58
On a side note, this will also allow me to refamilliarise myself with the templates after their changes in preparation for creating a woodland set for use on Chernarus, Livonia and any similar temperate maps.

**Comment by SonorousMeerkat** [comment] 2019-08-27 22:59
Currently the changes I laid out will be completed in 2 phases, and thus 2 separate pulls:
Phase 1 will be the changes to teamplayer including starting weapons, grenades and vests.
Phase 2 will be the rewrite for the AFRF Templates

Further from this i will begin creating a new set of standardized loadouts named based on the environment that they are suited for, Arid, Temperate and Tropical.

**Comment by SonorousMeerkat** [comment] 2019-08-27 23:03
A further standardization proposal is for the filenames: Side_Environment_Mod_Faction.sqf
For example Teamplayer_Arid_RHS_NAPA.sqf for the altis greenfor rebels

this saves us the barbolani names like teamplayerVanilla.sqf / teamplayerVanillaAltis / teamplayerVanillaAltisB

**Comment by Bob-Murphy** [comment] 2019-08-28 00:12
I would suggest to use Mod-Side-Environment-Faction - basically switch the position of Mod to the first place because most of the time you would work on them because for example the Mod updated.
Makes in my eyes a little bit more sense in terms of organisation.

**Comment by SonorousMeerkat** [comment] 2019-08-28 00:28
Seems fair to me, i considered having the game logic side be in the names too, Opfor, Blufor, Indfor. so you can tell blufor teamplayer templates apart slightly better if you aren't familiar with the faction names for all of the mods integrated.

**Comment by SonorousMeerkat** [comment] 2019-08-28 00:49
Under bob's idea,
RHS_Teamplayer_Ind_Arid_NAPA

**Comment by SonorousMeerkat** [comment] 2019-08-28 01:05
Potayto potaato, the template to template jumps are a barbolani thing that i nicked because i was copying files when i made 3cb

**Comment by SonorousMeerkat** [comment] 2019-08-28 01:07
And, tbf, if the names are changed the way i had them it would be a simple fix to update them
or you could bundle that with your initVAR/template stuff?

**Comment by SonorousMeerkat** [comment] 2019-09-06 17:34
I have made a project that outlines what all that i want to do and in what order i intend to do it.

**Comment by Bob-Murphy** [comment] 2019-10-21 11:00
@SonorousMeerkat 
Is this covered by your project?
If so, please connect the two.

**Comment by SonorousMeerkat** [comment] 2019-10-21 14:32
Some yes, some no. The gear (vests and rebel) is already pulled as per my project. The units are in progress. The new loot is Pot's system.

**Comment by Bob-Murphy** [comment] 2019-10-21 14:34
Please connect it to your project and close it when the rest is implemented.

**Comment by Bob-Murphy** [comment] 2020-03-27 18:41
@SonorousMeerkat 
Do we still need this issue as a separate one?
It's gonna be fixed by the template overhaul either way if not already happened.

**Comment by Bob-Murphy** [comment] 2020-03-27 18:47
Confirmed as dealt with by Meerkat

**Closed by Bob-Murphy** 2020-03-27 18:47 UTC
Labels: enhancement
