### ISSUE TITLE
_leader ERROR in the start of the mission

### ISSUE THREAD

**Issue by AlexTriada** [official-antistasi-community/A3-Antistasi#184] opened 2019-08-25 09:25 UTC
Version:* unstable branch

Mods: no

Environment: MP host, MP dedi.

have you edited the missionfile?: No

I find how to fix _leader ERROR in rpt:
`11:33:14 Error in expression <};
_leader = _possibleLeaders select 0;
_leader setvariable ["BIS_HC_scope",_log>
11:33:14   Error position: <_leader setvariable ["BIS_HC_scope",_log>
11:33:14   Error Неопределенная переменная в выражении: _leader
11:33:14 File A3\modules_f\HC\data\scripts\hc.sqf..., line 71`

look at the pic:

![Безымянный](https://user-images.githubusercontent.com/11041478/63648096-5f70d380-c733-11e9-9f00-8c22b07d5740.png)

**Comment by Toakan** [comment] 2019-08-30 16:14
Upstream issue, long ignored: 
https://github.com/A3Antistasi/A3-Antistasi/issues/198

**Comment by AlexTriada** [comment] 2019-08-31 07:13
thanks, but why ignore it if we can fix it?

**Comment by Bob-Murphy** [comment] 2019-08-31 07:16
We ignored it because it's not gamebreaking and we focus on that mainly ;)
Of course you can try to fix it

**Comment by Bob-Murphy** [comment] 2019-09-05 14:49
Tested and merged.

**Comment by Toakan** [comment] 2019-10-31 14:54
This has re-emerged in Unstable 2.2

```SQF
Error in expression <};
_leader = _possibleLeaders select 0;
_leader setvariable ["BIS_HC_scope",_log>
  Error position: <_leader setvariable ["BIS_HC_scope",_log>
  Error Undefined variable in expression: _leader
```

**Comment by wurzel0701** [comment] 2020-02-25 10:26
I am not aware of this happening anymore, anyone still has this error?

**Comment by Toakan** [comment] 2020-03-18 08:16
Yeah here you go, just pulled from unstable and ran it this morning without any additional addons / mods.
Line 702: 
```
8:14:48 Game started.
Error in expression <};
_leader = _possibleLeaders select 0;
_leader setvariable ["BIS_HC_scope",_log>
  Error position: <_leader setvariable ["BIS_HC_scope",_log>
  Error Undefined variable in expression: _leader
File A3\modules_f\HC\data\scripts\hc.sqf..., line 71
Attempt to override final function - bis_fnc_storeparamsvalues_data
```

[TEST1584519261.log](https://github.com/official-antistasi-community/A3-Antistasi/files/4347750/TEST1584519261.log)

**Comment by AlexTriada** [comment] 2021-01-30 02:21
This is not happened anymore

**Comment by AlexTriada** [comment] 2021-01-30 02:24
I think @Toakan has old mission.sqm in his test folder when this happened for some reasons

**Comment by Toakan** [comment] 2021-02-09 13:47
@AlexTriada Fresh pulls were done daily and confirmed as an issue by others on the team at the time. Something in your original fix was reverted or the fix did not do what was expected.

**Comment by Toakan** [comment] 2021-02-09 13:50
An RPT report from the Dev channles still shows this as an issue.

`2021/01/23,  8:00:14 No player found for channel 1932010496768 - message ignored
2021/01/23,  8:00:14 Error in expression <};
_leader = _possibleLeaders select 0;
_leader setvariable ["BIS_HC_scope",_log>
2021/01/23,  8:00:14   Error position: <_leader setvariable ["BIS_HC_scope",_log>
2021/01/23,  8:00:14   Error Undefined variable in expression: _leader
2021/01/23,  8:00:14 File A3\modules_f\HC\data\scripts\hc.sqf..., line 71
2021/01/23,  8:00:14 Attempt to override final function - bis_fnc_storeparamsvalues_data
2021/01/23,  8:00:15 "armahosts/BIS_fnc_log: [module] zen_modules_fnc_bi_moduleCurator (1173 ms)"
2021/01/23,  8:00:16 Strange convex component116 in a3\rocks_f\sharp\sharprock_apart.p3d:geometryFire`

[arma3server_x64_2021-01-23_07-57-33.zip](https://github.com/official-antistasi-community/A3-Antistasi/files/5951740/arma3server_x64_2021-01-23_07-57-33.zip)

**Comment by killerswin2** [comment] 2021-12-21 02:38
this HC BIS bug is fixed now. Reopen if persistence.

**Closed by killerswin2** 2021-12-21 02:38 UTC
Labels: bug
