### ISSUE TITLE
Airports don't spawn helicopters

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#333] opened 2019-09-22 18:43 UTC
Possibly to due with '_busy' and A3A_fnc_addTimeForIdle from Patrols.

**Comment by Spoffy** [comment] 2019-09-22 18:44
Same for Attack vehicles (line 304)

**Comment by wurzel0701** [comment] 2019-09-26 05:12
As I currently change it in #289, should I remove the busy flag?
Another thing that keeps units from spawning is the available mechanics.
Most vehicles are simply not available most times

**Comment by wurzel0701** [comment] 2019-09-27 07:09
Its not a bug the game mechanics are working as they should.

The game mechanic may not be that good in this point...

**Comment by wurzel0701** [comment] 2019-09-29 16:32
Fixed in #345

**Closed by wurzel0701** 2019-09-29 16:32 UTC
Labels: info needed
