### ISSUE TITLE
PAKs not loading into loadouts

### ISSUE THREAD

**Issue by Spoffy** [official-antistasi-community/A3-Antistasi#340] opened 2019-09-28 01:11 UTC
When loading a saved loadouts, PAKs don't load from the arsenal, despite being infinite. Claims they're missing.

**Comment by PoweredByPot** [comment] 2019-09-30 19:35
found the cause by accident during the rest of my loot crate part 2

**Comment by Spoffy** [comment] 2019-09-30 20:42
What was the cause?

**Comment by PoweredByPot** [comment] 2019-09-30 21:29
https://github.com/official-antistasi-community/A3-Antistasi/blob/7a90557f97399bcb6c828d97e377d31de81e7bd2/A3-Antistasi/JeroenArsenal/JNA/fn_arsenal_itemType.sqf#L139

_itemType should have been _itemInfoType

**Comment by Spoffy** [comment] 2019-09-30 23:43
Sweet. I'll patch that now.

**Comment by Spoffy** [comment] 2019-09-30 23:43
It doesn't look like it'd cause the issue to me, but I'm happy to be wrong here.

**Comment by Bob-Murphy** [comment] 2019-10-21 12:02
@Spoffy 
Update/Milestone?

**Comment by PoweredByPot** [comment] 2019-10-21 13:42
unable to re-create, likely fixed on accident.

**Closed by PoweredByPot** 2019-10-21 13:42 UTC
Labels: bug
