### ISSUE TITLE
[Bug]: You can garage land vehicles at any rebel marker

### ISSUE THREAD

**Issue by Callum511** [official-antistasi-community/A3-Antistasi#2029] opened 2021-08-03 15:23 UTC
### Describe the bug

You can garage land vehicles at any rebel marker. Ex, roadblocks, enemy roadblocks that get destroyed, etc.
Garaging should be limited to friendly main objectives aka outposts, airfields, seaports etc

### How to reproduce

Go to any roadblock and destroy it, clear the area of enemies, then park a vehicle where the roadblock was and garage it 

### Version

2.5

### Have you altered the code?

No

### Map

All

### What server?

Community Server 1

### Time bug occured (Server time/UTC)

N/A

**Comment by Lazejun** [comment] 2021-08-03 15:40
Duplicate of #605

**Comment by jaj22** [comment] 2021-08-09 14:52
Sort of. I didn't realise that roadblocks worked until recently.

Cities are more of an issue though, because once you figure that they work, it's trivial to go grab a pile of free vehicles. Now that the commander buys them with faction money it's a bit much.

I would be inclined to allow factories/resources.

**Comment by jaj22** [comment] 2021-09-26 16:03
Resolved by #2107.

**Closed by jaj22** 2021-09-26 16:03 UTC
Labels: bug, Merge pending
