### ISSUE TITLE
[Bug]: AI Temp control bug

### ISSUE THREAD

**Issue by debug420** [official-antistasi-community/A3-Antistasi#2264] opened 2022-02-18 07:23 UTC
### Describe the bug

Returning out of AI temp control does not allow you to go into "AI management" of other squads and assumes that you are no longer the group leader.

### How to reproduce

1. Recruit squad
2. Select squad in HC
3. Y -> AI Management
4. AI Temp Control
5. Return out of AI Temp Control
6. Y -> AI Management (it doesn't allow you to go into AI management)

### Version

2.5.3

### Have you altered the code?

No

### Map

Tanoa

### What server?

LAN Hosted

### Mods

```html
Vanilla
```

**Comment by jaj22** [comment] 2022-02-19 17:18
Can't replicate. Are you missing some details? I don't think it's even possible to not be group leader if you're the only unit in your group.

**Comment by DelanoBrouwer** [comment] 2022-09-27 09:33
Unable to reproduce. Attempted with another player in group on DS over varying ranges. Also tried while just letting the AI timer run out.

**Comment by jaj22** [comment] 2023-04-13 15:48
Closing, probably conflicting mod.

**Closed by jaj22** 2023-04-13 15:48 UTC
Labels: bug, triage
