### ISSUE TITLE
Tanoa:  NATO attacks are announced, but never arrive - announcement remains until server reset

### ISSUE THREAD

**Issue by Mirv** [official-antistasi-community/A3-Antistasi#1428] opened 2020-09-04 19:17 UTC
**Describe the bug**
NATO attacks are announced, but never arrive

**To Reproduce**
This is a longer running issue to track.  Nothing short of you running a map, taking zones and watching for a week will likely show this issue.  I don't know what logging events would even specify conquest etc, so not sure how to advise.

**Expected behaviour**
At some point we expect to have something attacked by NATO.  We have garrisoned and non-garrisoned resources, outputs, cities.  Nothing in 3+ weeks has been taken back & a majority of that time we had 0 garrisons.

**Screenshots**

**Environment (please complete the following information):**
Version: 2.3.0 
Map (specify if Altis Blufor): Tanoa

[ ] LAN Hosted
[ ] Private dedicated server
[ ] Private dedicated server with Headless client(s)
[ ] Community Server 1
[ ] Community Server 2
[ ] Community Test Server
[ ] Community Test Server 2
[x] Other - Publicly professionally hosted on HostHavoc (=JpS= Llama is Reborn! 216.105.171.156:2302 if you want to try tracking yourself too)

Modset:
    
Time the bug occurred (Please leave in GMT+0):
If **Not** on a community server, please leave the time zone of your client for LAN, or the server for dedicated: 

**Additional context**

If you were LAN hosting, please attach your client .RPT file from when the bug occurred, If on a private dedicated server, please attach the server's .RPT from when the bug occurred.

---
Log file -
https://discordapp.com/channels/449481990513754112/647694189236322305/751517079059824661

**Comment by jaj22** [comment] 2020-09-04 20:01
Duplicate of #1401

**Closed** 2020-09-04 20:14 UTC
Labels: bug
