### ISSUE TITLE
[Bug]: Mission doesn't start

### ISSUE THREAD

**Issue by zayfix** [official-antistasi-community/A3-Antistasi#2219] opened 2022-01-22 13:12 UTC
### Describe the bug

Mission won't start, you spawn at initial base with basic things (arsenal, garage, etc) but nothing works and the mission doesn't load more.

### How to reproduce

- Git clone the repo (d6d68ef)
- Build the mission with powershell
- Start game with mods ( list below )
- Start the mission

### Version

Latest github commit, not a version

### Have you altered the code?

No

### What i have changed

Changed nothing just looked up the error, it looks like it come from this [line](https://github.com/official-antistasi-community/A3-Antistasi/blob/unstable/A3-Antistasi/functions/Templates/fn_loadAddon.sqf#L26}).

### Map

Altis

### What server?

LAN Hosted

### Mods

```html
CBA_A3 	                                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=450814997
RKSL Studios - Attachments v3.02 	            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1661066023
RHSUSAF 	                                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=843577117
RHSAFRF 	                                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=843425103
3CB BAF Equipment 	                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=893328083
3CB BAF Vehicles 	                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=893349825
Enhanced Movement 	                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=333310405
3CB BAF Weapons 	                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=893339590
RHSGREF 	                                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=843593391
RHSSAF 	                                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=843632231
JSRS SOUNDMOD 	                                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=861133494
GGE: Core 	                                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2010222986
Reduced Haze Mod v3.1 	                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1397683809
Real Engine 	                                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2127693591
Enhanced Missile Smoke + Lighting Efx Mod v1.4 	    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1484261993
3CB BAF Units 	                                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=893346105
Enhanced Visuals 	                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=880703327
Bullet Casings 	                                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=606289254
RDS Civilian Pack 	                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=612930542
RS - Rain Textures 	                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=748534644
Enhanced GPS 	                                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2480263219
Ragdoll Physics Plus+ v1.12 	                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2290838143
Blastcore Murr Edition 	                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2257686620
Enhanced Map 	                                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2467589125
Project SFX: Remastered 	                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2129532219
Unit Voice-overs 	                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1868302880
3CB BAF Vehicles (RHS reskins) 	                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1515851169
3CB BAF Vehicles (Servicing extension) 	            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1135543967
JSRS SOUNDMOD - RHS AiO Mod Pack Sound Support 	    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2068033599
No More Aircraft Bouncing 	                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1770265310
Enhanced Movement Rework 	                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2034363662
3CB Factions 	                                    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1673456286
JSRS SOUNDMOD - Reloading Sounds 	            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1429098683
GGE: NVG Animation 	                            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=2010225817
3CB BAF Units (RHS compatibility) 	            Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1135541175
3CB BAF Weapons (RHS ammo compatibility) 	    Steam 	http://steamcommunity.com/sharedfiles/filedetails/?id=1515845502
```

### Additional context

These are the last lines from .rpt
[Pastebin of full .rpt](https://pastebin.com/22zjpjhL)
[...]
13:49:25 Error in expression <ide);

private _addon = createHashMap;
call preprocessFileLineNumbers _path;

>
13:49:25   Error position: <call preprocessFileLineNumbers _path;

>
13:49:25   Error call: Type Chaîne, code attendu
13:49:25 File steamMPMission\__cur_mp.Altis\functions\Templates\fn_loadAddon.sqf..., line 26

**Comment by Lazejun** [comment] 2022-01-22 13:14
Please include the Full RPT.

**Comment by Lazejun** [comment] 2022-01-22 13:24
Fastest solution is not to use RDS Car Pack

**Comment by HakonRydland** [comment] 2022-01-22 13:29
Note we do not recommend using unstable

**Comment by zayfix** [comment] 2022-01-22 13:39
@Lazejun It works, thanks!
@HakonRydland Yea but that way i can try the latest commit.

Closing the issue.

**Comment by HakonRydland** [comment] 2022-01-22 13:41
issue not resolved, but will be shortly (as the cause is not resolved by not playing with the broken stuff) 😄

**Closed** 2022-01-23 14:42 UTC
Labels: bug
