### ISSUE TITLE
RHS headgear disappearing

### ISSUE THREAD

**Issue by JohnnyDeeee** [official-antistasi-community/A3-Antistasi#773] opened 2020-02-11 11:47 UTC
*Version:* 2.2.1

*Mods:* CBA_A3, RHSAFRF, RHSUSAF, ace, RHSGREF, ACE Compat - RHS Armed Forces of the Russian Federation, ACE Compat - RHS United States Armed Forces, ACE Compat - RHS- GREF, task_force_radio, BackpackOnChest, GRAD Trenches, CUP Terrains - Core, CUP Terrains - Maps, task_force_radio, CUP ACE3 Compatibility Addon - Terrains

*Environment*: MP dedi.

*.rpt attatched?* NO

*have you edited the missionfile?*: NO

***Issue:***

After killing a (antistasi spawned) unit, the headgear (helmets) disappear. This blocks us from gathering/unlocking helmets.

It might have something to do with https://github.com/official-antistasi-community/A3-Antistasi/blob/bc2604627ad4b46b2d826d89469eaa6e7464264f/A3-Antistasi/functions/Revive/fn_handleDamageAAF.sqf#L63-L66, but i have not done any testing on this..

**Comment by Lazejun** [comment] 2020-02-11 12:22
Blame Ace, its a known issue since Aces Update

**Comment by JohnnyDeeee** [comment] 2020-02-11 12:34
EDIT: I updated the permalink

@Lazejun is there any known workaround?

**Comment by Lazejun** [comment] 2020-02-11 12:41
I am pretty sure someone was looking for something so it doesent eat them with ace but SoonTM so try removing that Line for the Time and see if it works :)

**Comment by JohnnyDeeee** [comment] 2020-02-11 12:43
Can confirm that removing the if works.
I'll try to find a way where i can recognize the ACE version and combine it with the if-statement

**Comment by wurzel0701** [comment] 2020-02-11 13:03
Afaik ACE seems to kill the unit with damage applied to the head if the unit dies. The Antistasi code will catch this case and assume that the unit has taken a headshot. As long as ACE keeps doing this, there is not much we can do to keep helmets in place, besides deactivating this code completely. We are looking for a workaround, but there is not much hope.

**Comment by jaj22** [comment] 2020-02-11 19:20
This is caused by ACE medical adding a dummy hitpoint with the selection name of "head", for some reason. If you want to retain helmet popping then you can work around it by using the hitpoint name ("hithead") rather than the selection name in the damage handler. 

It's fixed in my ACE medical integration patch which should be PR'd soon(tm).

**Closed** 2020-02-23 11:03 UTC
Labels: Merge pending, bug
