### ISSUE TITLE
Feature suggestion: Force auto-mount button for garrisoned units

### ISSUE THREAD

**Issue by ShoppyCodes** [official-antistasi-community/A3-Antistasi#1958] opened 2021-05-26 18:02 UTC
**Is your feature request related to a problem? Please describe.**
Currently, to auto-mount garrisoned units onto static weapons you have to have all players leave the area and then come back. When you have even a small amount of players there are often people at HQ/other outposts blocking the auto-mount thing that happens for the garrisoned units and static weapons/HMG emplacements etc.

**Describe the solution you'd like**
Is it possible to have a "force garrisoned AI to mount statics at this outpost" button?

This would be very useful when making statics at HQ/other outposts. When you have even a small amount of players there are often people at HQ blocking the auto-mount thing that happens.

**Describe alternatives you've considered**
Possibly this could just be available by the commander.

**Additional context**
N/A

Note: Also suggested on the Discord suggestions channel.

**Comment by Lazejun** [comment] 2021-05-26 18:03
duplicate of #972

**Closed by Lazejun** 2021-05-26 18:03 UTC
Labels: Suggestion, enhancement
