### ISSUE TITLE
Open testing error 10 – Unloading in vehicle box not working

### ISSUE THREAD

**Issue by Bob-Murphy** [official-antistasi-community/A3-Antistasi#552] opened 2019-11-24 23:57 UTC
**### Please assign yourself to the issue or comment your name when you start working on it.**

2.2 has added an arsenal to the vehicle box so vehicles can load with it.
When a players enders the arsenal via the vehicle and empties it by hand, the items get put into the arsenal.
BUT
When selecting the "unload vehicle" option on the box all the inventory get's lost completely.

This needs to be fixed.

**Comment by Spoffy** [comment] 2019-11-25 00:24
Duplicate of #535 - Already fixed

**Closed by Spoffy** 2019-11-25 00:24 UTC
Labels: Priority, bug
