### ISSUE TITLE
Vehicle icons showing as APC when they're not

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1159] opened 2020-06-22 04:30 UTC
*Version:* Unstable

*Mods:* Any?

*Environment*: Any?

***Issue:***
Apparently these units are not APCs or something:

![20200620204845_1](https://user-images.githubusercontent.com/562040/85248621-41562b80-b449-11ea-8c0d-d2fc8b6b35f8.jpg)

This issue description is shit because apparently Wurzel knows what the problem is and so it's a waste of time for me to investigate it.

**Comment by wurzel0701** [comment] 2020-06-22 11:03
As the problem is purely visual, it wont be fixed for 2.2.2/2.3.

If anyone is interested in having it in PR #1150 fixes it, but needs two PRs before that to work

**Closed** 2020-09-09 09:01 UTC
Labels: Merge pending, bug
