### ISSUE TITLE
[Bug]: Sometimes Airfield defense units take off too fast after spawning

### ISSUE THREAD

**Issue by MeltedPixel** [official-antistasi-community/A3-Antistasi#2880] opened 2023-07-29 19:16 UTC
### Describe the bug

Sometimes Airfield defense units take off too fast after spawning, shouldn't do that.

### How to reproduce

Go to airbase.
Let vehicles spawn.
Watch AA vehicle take off right away.

### Version

3.3

### Have you altered the code?

No

### Map

Altis

### What server?

LAN Hosted

**Comment by ante185** [comment] 2023-08-27 20:29
![image](https://github.com/official-antistasi-community/A3-Antistasi/assets/49555217/4a1136d7-c0e8-42a7-a0d1-fe8a2825f104)
Molos Airfield, Altis
usually the consequence is much more explosive

**Comment by Tiny-DM** [comment] 2024-01-23 22:44
Duplicate of #3074 , fixed in #3102 .

**Closed by Tiny-DM** 2024-01-23 22:44 UTC
Labels: Bug, Triage
