### ISSUE TITLE
[Bug]: AFRF (RHS) attacks cause crashes on Linux servers

### ISSUE THREAD

**Issue by jaj22** [official-antistasi-community/A3-Antistasi#1385] opened 2020-08-09 17:35 UTC
**Describe the bug**
There are several reports of AFRF attacks causing Arma crashes on Linux servers. This is probably an RHS bug with a specific vehicle, but we can work around the problem if it's only one broken vehicle.

Recent evidence suggests that `RHS_Mi8MTV3_vvsc` is likely to be the cause.

**To Reproduce**
AFRF attacks are the common connection, although not every wave will generate one of every vehicle, so you may need a few attempts. On a clean Altis start, this should work. Run as server:

`["airport_3", "airport_2", 3] spawn A3A_fnc_wavedCA`

**Environment (please complete the following information):**
Version: Probably doesn't matter
Map (specify if Altis Blufor): Probably doesn't matter
Modset: RHS greenfor
Linux dedicated server only.

**Comment by Jacob-Steentoft** [comment] 2020-09-05 20:45
We're encountering similar issues on our end where RHS attacks has crashed our server twice. Sadly can't link any events directly to the crash itself from the logs.

**Comment by jaj22** [comment] 2020-09-06 01:14
@Jacob-Steentoft
I'm interested in any server RPTs from 2.3 where the server crashed shortly after an attack started. We don't have sufficiently conclusive evidence to remove vehicles yet.

**Comment by Jacob-Steentoft** [comment] 2020-09-06 09:12
@jaj22 
[Crashes.txt](https://github.com/official-antistasi-community/A3-Antistasi/files/5179313/Crashes.txt)
The 2 crashes happens before:
Line 65000: watchdog (30399): [Sat 05 Sep 2020 08:12:46 PM CEST] server died, waiting to restart...
Line 67619: watchdog (30399): [Sat 05 Sep 2020 08:53:16 PM CEST] server died, waiting to restart...

**Comment by Bob-Murphy** [comment] 2020-09-06 10:38
Should be fixed LATEST in 2.4, I prefer earlier.

**Comment by jaj22** [comment] 2020-09-06 22:24
Crash at 20:12, wave spawns at 20:03 and 20:11. Vehicles classes used:
RHS_Mi8mt_vvsc
RHS_Mi8AMT_vvsc
RHS_ka60_c
rhs_mi28n_vvs
RHS_Mi8AMTSh_vvsc
RHS_Mi24P_vvsc
rhs_pchela1t_vvsc

Crash at 20:53, wave spawn at 20:47. Vehicles classes used:
RHS_Mi8MTV3_vvsc
RHS_ka60_c
RHS_Mi8mt_vvsc
RHS_Mi24P_vvsc
rhs_mig29s_vvs
rhs_pchela1t_vvsc

Aircraft used in wavedCAs that didn't crash:

rhs_mi28n_vvs
RHS_Su25SM_CAS_vvs
rhs_mig29s_vvs
rhs_pchela1t_vvsc (x2)
RHS_Mi8AMTSh_vvsc (x2)
RHS_Mi8mt_vvsc (x2)
rhs_ka60_c (x2)

It looks like it doesn't necessarily crash for several minutes after the aircraft spawn, so looking at the last spawned vehicle isn't useful and so the Mi8MTV3 was probably a red herring. The current prime suspect is the Mi24P on this information (2 crashes out of 2 appearances), although it's still possible that multiple vehicles may be affected or it's not specific vehicles causing the crashes at all. Will need more information.

**Comment by SpiReCZ** [comment] 2020-09-07 10:46
We tried to remove `RHS_Mi8MTV3_vvsc` on our dedicated Linux server. The result was less frequent crashes, but there were still situations where the server crashed.

Finally we were forced to migrate our Linux installation to Windows binaries under Wine to be able to run the server without crashes.

**Comment by Jacob-Steentoft** [comment] 2020-09-09 20:24
Are more logs needed? We got another 2 crashes today

**Comment by jaj22** [comment] 2020-09-09 23:46
@Jacob-Steentoft Yes, as many as possible please.

**Comment by Jacob-Steentoft** [comment] 2020-09-12 15:22
[Crashes 2.log](https://github.com/official-antistasi-community/A3-Antistasi/files/5212882/Crashes.2.log)
@jaj22 
The 2 crashes happens before:
Line 116998: watchdog (5020): [Wed 09 Sep 2020 07:23:38 PM CEST] server died, waiting to restart...
Line 119244: watchdog (5020): [Wed 09 Sep 2020 07:36:23 PM CEST] server died, waiting to restart...

**Comment by jaj22** [comment] 2020-09-13 04:52
Ok, looks like it's not a specific vehicle. Can't spot any relationship between the crashes, non-crashes and the vehicles used.

I don't have any further ideas at the moment on how to approach this. Can't think of anything that's not massively labor-intensive and probably futile anyway. Even if we do figure out the cause, there's not likely to be anything we can do if it's not specific vehicles at fault.

**Comment by Jacob-Steentoft** [comment] 2020-09-13 09:15
Is there anything we can do to remove the Russians? The issue is getting worse and worse on the server as they keep attacking the US.

**Comment by jaj22** [comment] 2020-09-13 16:23
@Jacob-Steentoft Run this as server:

```
{
    if (sidesX getVariable [_x, sideUnknown] == Invaders) then { [Occupants, _x] spawn A3A_fnc_markerChange };
} forEach (airportsX + outposts + factories + resourcesX + seaports);
gameMode = 3; publicVariable "gameMode";
```

**Closed** 2024-04-22 14:40 UTC
Labels: Priority, Change
