### ISSUE TITLE
[Bug]: Fast Travel to friendly Position not working anymore

### ISSUE THREAD

**Issue by SockenSalat** [official-antistasi-community/A3-Antistasi#3201] opened 2024-04-05 08:01 UTC
### Describe the bug

Despite being enabled in settings, fast travel for player groups is only allowed to HQ and Airport.

I hope this is not intentional.

### How to reproduce

Just start a new Mission with the setting to _any friendly position_, create an Outpost and try to travel fast ...

### Version

v3.5.2

### Have you altered the code?

No

### Map

Any

### What server?

LAN Hosted

### Mods

```html
Reaction Forces DLC
```

**Comment by SockenSalat** [comment] 2024-04-05 08:03
duplicate of https://github.com/official-antistasi-community/A3-Antistasi/issues/3193#issue-2217908267

**Comment by destroyer3252** [comment] 2024-04-07 14:26
I am also having this issue but I do not have the reaction forces DLC enabled. ARMA 3 is fully updated and everything was working prior perfectly fine. I am using RHS and 3CB along with some other mods. But once again, everything was working fine beforehand.

**Comment by ante185** [comment] 2024-04-07 15:09
Closing as duplicate of #3193, PR #3196 fixes this issue.

**Closed by ante185** 2024-04-07 15:09 UTC
Labels: Duplicate
